# ============================================================
# configs/train.yaml — Train config
# Dùng: model.train("configs/train.yaml")
# ============================================================

model_yaml: dualattention_glkaV1.yaml      # relative so với file này hoặc absolute
data:       dataset.yaml  # relative so với project root

img_size: 224

normalize:
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]

augment:
  crop_scale: [0.7, 1.0]
  flip_h:     0.5
  flip_v:     0.3
  color_jitter:
    brightness: 0.3
    contrast:   0.3
    saturation: 0.2
    hue:        0.05

train:
  epochs:     150
  batch_size: 64
  seed:       42
  val_ratio:  0.2      # dùng khi không có val: trong dataset.yaml -> tự tách từ train_set
  test_ratio: 0         # để 0 vì test_set đã tách vật lý sẵn trên đĩa, không cần loader tự chia nữa
  handle_imbalance: true
  label_smoothing:  0.0

  optimizer:
    type:         SGD
    lr:           0.01
    momentum:     0.9
    weight_decay: 0.0005
    nesterov:     true

  scheduler:
    type:    CosineAnnealingLR
    eta_min: 0.000001

hardware:
  device:      cuda
  num_workers: 8
  pin_memory:  true

logging:
  runs_dir:      runs
  tsne_interval: 20
  eval_test:     true

export:
  enabled: true
  opset:   18
  export_tflite: true
  tflite_mode:   all
  n_calib:       200
  test_dir: "C:/Users/ThisPC/Desktop/Raw Data/CCMT Dataset/test_set"
  tflite_project_dir: "C:/Users/ThisPC/Documents/GitHub/Simple_GLKA/TFlite"
  dataset_yaml: "glkanet/configs/dataset.yaml"    # ← dòng mới thêm